### ISSUE TITLE
Question about data_root 

### ISSUE THREAD

**Issue by Roywangj** [laoreja/HPLFlowNet#27]
Hi:
       Recently, I I have tried test HPLFlowNet on KITTI dataset with pretrained model. I noticed that data_root is not being read in config file. I set 'data_root: /home1/users/wangjie/sceneflow/HPLFlowNet-master/SAVE_PATH/KITTI_processed_occ_final/'  in the end of the config file 'test_ours_KITTI.yaml'.  However when i run the program, error happened as follows:  

assert (len(useful_paths) == 200) failed! 0
mapping_path /home1/users/wangjie/sceneflow/HPLFlowNet-master/datasets/KITTI_mapping.txt
Traceback (most recent call last):
  File "main.py", line 290, in <module>
    main()
  File "main.py", line 82, in main
    args=args
  File "/home1/users/wangjie/sceneflow/HPLFlowNet-master/datasets/kitti.py", line 35, in __init__
    raise (RuntimeError("Found 0 files in subfolders of: " + self.root + "\n"))
RuntimeError: Found 0 files in subfolders of: sceneflow/HPLFlowNet-master/SAVE_PATH/KITTI_processed_occ_final

I don't know if the root_data is wrong or there are some other questions unpredicted. 
Would you kindly help me?

**Comment by Roywangj** [comment]
Issue solved. When i check codes carefully, i found i wrongly set data_root concatened  with KITTI_processed_occ_final. The rights set is : HPLFlowNet-master/SAVE_PATH/. 
I hope it can help others
